// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.8.0
// source: proto/reaperconfig.proto

package reaperconfig

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResourceType int32

const (
	ResourceType_GCE_VM     ResourceType = 0
	ResourceType_GCS_BUCKET ResourceType = 1
	ResourceType_BIGQUERY   ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "GCE_VM",
		1: "GCS_BUCKET",
		2: "BIGQUERY",
	}
	ResourceType_value = map[string]int32{
		"GCE_VM":     0,
		"GCS_BUCKET": 1,
		"BIGQUERY":   2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reaperconfig_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_proto_reaperconfig_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_reaperconfig_proto_rawDescGZIP(), []int{0}
}

type ReaperCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*ReaperConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *ReaperCluster) Reset() {
	*x = ReaperCluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reaperconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReaperCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaperCluster) ProtoMessage() {}

func (x *ReaperCluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reaperconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaperCluster.ProtoReflect.Descriptor instead.
func (*ReaperCluster) Descriptor() ([]byte, []int) {
	return file_proto_reaperconfig_proto_rawDescGZIP(), []int{0}
}

func (x *ReaperCluster) GetConfigs() []*ReaperConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ReaperConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources  []*ResourceConfig `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Schedule   string            `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	SkipFilter string            `protobuf:"bytes,3,opt,name=skip_filter,json=skipFilter,proto3" json:"skip_filter,omitempty"`
	ProjectId  string            `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Uuid       string            `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ReaperConfig) Reset() {
	*x = ReaperConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reaperconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReaperConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaperConfig) ProtoMessage() {}

func (x *ReaperConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reaperconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaperConfig.ProtoReflect.Descriptor instead.
func (*ReaperConfig) Descriptor() ([]byte, []int) {
	return file_proto_reaperconfig_proto_rawDescGZIP(), []int{1}
}

func (x *ReaperConfig) GetResources() []*ResourceConfig {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ReaperConfig) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *ReaperConfig) GetSkipFilter() string {
	if x != nil {
		return x.SkipFilter
	}
	return ""
}

func (x *ReaperConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ReaperConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ResourceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceType ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=reaperconfig.ResourceType" json:"resource_type,omitempty"`
	NameFilter   string       `protobuf:"bytes,2,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"`
	SkipFilter   string       `protobuf:"bytes,3,opt,name=skip_filter,json=skipFilter,proto3" json:"skip_filter,omitempty"`
	Zones        []string     `protobuf:"bytes,4,rep,name=zones,proto3" json:"zones,omitempty"`
	Ttl          string       `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reaperconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reaperconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_proto_reaperconfig_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceConfig) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_GCE_VM
}

func (x *ResourceConfig) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

func (x *ResourceConfig) GetSkipFilter() string {
	if x != nil {
		return x.SkipFilter
	}
	return ""
}

func (x *ResourceConfig) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ResourceConfig) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

var File_proto_reaperconfig_proto protoreflect.FileDescriptor

var file_proto_reaperconfig_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x61, 0x70, 0x65, 0x72, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x61, 0x70,
	0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x45, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x70,
	0x65, 0x72, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x61,
	0x70, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x70, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22,
	0xba, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x3a, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x61, 0x70, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x70,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x6b, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0xbb, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x3f, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x61, 0x70, 0x65, 0x72, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x2a, 0x38, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x43,
	0x45, 0x5f, 0x56, 0x4d, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x43, 0x53, 0x5f, 0x42, 0x55,
	0x43, 0x4b, 0x45, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x49, 0x47, 0x51, 0x55, 0x45,
	0x52, 0x59, 0x10, 0x02, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73,
	0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x61, 0x69, 0x2d, 0x67, 0x63, 0x70, 0x2d, 0x74, 0x65, 0x73,
	0x74, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x61, 0x70, 0x65,
	0x72, 0x2f, 0x72, 0x65, 0x61, 0x70, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reaperconfig_proto_rawDescOnce sync.Once
	file_proto_reaperconfig_proto_rawDescData = file_proto_reaperconfig_proto_rawDesc
)

func file_proto_reaperconfig_proto_rawDescGZIP() []byte {
	file_proto_reaperconfig_proto_rawDescOnce.Do(func() {
		file_proto_reaperconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reaperconfig_proto_rawDescData)
	})
	return file_proto_reaperconfig_proto_rawDescData
}

var file_proto_reaperconfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_reaperconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_reaperconfig_proto_goTypes = []interface{}{
	(ResourceType)(0),      // 0: reaperconfig.ResourceType
	(*ReaperCluster)(nil),  // 1: reaperconfig.ReaperCluster
	(*ReaperConfig)(nil),   // 2: reaperconfig.ReaperConfig
	(*ResourceConfig)(nil), // 3: reaperconfig.ResourceConfig
}
var file_proto_reaperconfig_proto_depIdxs = []int32{
	2, // 0: reaperconfig.ReaperCluster.configs:type_name -> reaperconfig.ReaperConfig
	3, // 1: reaperconfig.ReaperConfig.resources:type_name -> reaperconfig.ResourceConfig
	0, // 2: reaperconfig.ResourceConfig.resource_type:type_name -> reaperconfig.ResourceType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_reaperconfig_proto_init() }
func file_proto_reaperconfig_proto_init() {
	if File_proto_reaperconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reaperconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReaperCluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reaperconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReaperConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reaperconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reaperconfig_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reaperconfig_proto_goTypes,
		DependencyIndexes: file_proto_reaperconfig_proto_depIdxs,
		EnumInfos:         file_proto_reaperconfig_proto_enumTypes,
		MessageInfos:      file_proto_reaperconfig_proto_msgTypes,
	}.Build()
	File_proto_reaperconfig_proto = out.File
	file_proto_reaperconfig_proto_rawDesc = nil
	file_proto_reaperconfig_proto_goTypes = nil
	file_proto_reaperconfig_proto_depIdxs = nil
}
